name: Build BioAgent Binary

on:
  workflow_run:
    workflows: ["Build and push"]
    types: [completed]
    branches: ["main"]

permissions:
  contents: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-bioagent-binary:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download dockerc
        run: |
          curl -fLo dockerc https://github.com/NilsIrl/dockerc/releases/download/v0.3.2/dockerc_x86-64
          chmod +x ./dockerc
      - name: Build binary
        run: ./dockerc --image ghcr.io/${{ github.repository }}:main --output bioagents_bin
