name: Build BioAgent Binary

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository }}

jobs:
  build-bioagent-binary:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download dockerc
        run: |
          curl -fLo dockerc https://github.com/NilsIrl/dockerc/releases/download/v0.3.2/dockerc_x86-64
          chmod +x ./dockerc

      - name: Set lowercase repository name
        id: repo-name
        run: |
          LOWERCASE_REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "LOWERCASE_REPO=${LOWERCASE_REPO}" >> $GITHUB_ENV

      - name: Build binary
        run: ./dockerc --image docker://${REGISTRY}/${LOWERCASE_REPO}:main --output bioagents_bin
